[package]
name = "fastabterm2"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
fastab_ipc.workspace = true
fastab_proto.workspace = true
fastab_remote_ipc.workspace = true
fastab_util.workspace = true
portable-pty.workspace = true
tempfile.workspace = true
tokio.workspace = true
uuid.workspace = true
